### ISSUE TITLE
KeyError: 'start'

### ISSUE THREAD

**Issue by fswirsky** [beroukhim-lab/BISCUT-py3#4] opened 2023-09-12 10:54 UTC
Hi,

I've been trying to get BISCUT to work on my environment and I was able to complete the tutorial no problem using the 'PANCAN_ISAR.seg.txt' segmentation file provided. However, I am now trying to run the preprocessing script on my data and the same errors keeps on appearing:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/user/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'start'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Miniconda3/4.9.2/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "BISCUT_preprocessing.py", line 37, in do_arm
    psedftel = get_percent_start_end(aneu, arm, coord, '~/BISCUT-py3/docs/' + tumortype + seg_file_suffix, threshold, 'tel', False)
  File "BISCUT_preprocessing.py", line 155, in get_percent_start_end
    psedf['start']=psedf['start'].apply(lambda x: min(1,max(0.0,(x-coord[0])/len_arm)))
  File "/user/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/user/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'start'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "BISCUT_preprocessing.py", line 246, in <module>
    take_care_arms(tumor_type, date_suffix)
  File "BISCUT_preprocessing.py", line 241, in take_care_arms
    result.get(9999999)
  File "/Miniconda3/4.9.2/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 'start'
```

I have been trying to find where the key is but I'm not the most proficient at python so maybe I am missing something, but cannot find the source of where this 'start' key is. My data is formatted identically to the sample data with these columns:

Sample	Chromosome	Start	End	Num_Probes	Segment_Mean

The script is the same I used for the sample data, except I have changed the tumour_type to OAC and seg_file_suffix to '_seg.txt'; the file I am using is called 'OAC_seg.txt'

Any help is greatly appreciated.

**Comment by shahab-sarmashghi** [comment] 2023-09-12 13:38
Hi,

Are you using the latest version of the code https://github.com/beroukhim-lab/BISCUT-py3/releases/tag/v1.2.0? It's similar to the error that was resolved in the latest release so I wonder it's the same issue or something else

**Comment by fswirsky** [comment] 2023-09-12 14:31
Hi,
I've run the latest version of the code and now in R rather than submitting it to the HPC, and getting this error:

```
Error in py_call_impl(callable, call_args$unnamed, call_args$named) :
ValueError: No objects to concatenate
Run `reticulate::py_last_error()` for details.
> reticulate::py_last_error()

── Python Exception Message ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
TypeError: 'function' object is not subscriptable

── R Traceback ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     ▆
  1. └─.rs.environment.isSuspendable()
  2.   ├─base::tryCatch(...)
  3.   │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
  4.   │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
  5.   │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
  6.   └─.rs.environment.isSuspendableImpl(globalenv(), 1L)
  7.     └─.rs.environment.isSuspendableImpl(value[[key]], depth + 1L)
  8.       ├─.rs.environment.isSuspendableImpl(value[[i]], depth + 1L)
  9.       ├─value[[i]]
 10.       └─reticulate:::`[[.python.builtin.object`(value, i)
 11.         └─reticulate:::py_get_attr_or_item(x, name, FALSE)
 12.           └─reticulate::py_get_item(x, name)
 13.             └─reticulate:::py_get_item_impl(x, key, silent)
```

Looking through my results_*date*_0.95 folder there is only my CANCERTYPE folder (OAC) - which contains only 5 arm .pdf graphs, a similar stats folder for the same arms, and KS_pvalues_*date*_0.95.txt

**Comment by fswirsky** [comment] 2023-09-12 14:48
Alos, I'm not sure if this is related, but all of my breakpoint files are basically the same and each row is almost identical with no variation - and I know from other pipelines I've run that there are definitely arm-level copy number changes with this data. I also noticed on the tutorial data set the Segment_Mean was sometimes negative, but I'm not sure how this is possible if the ploidy and CN values are always going to be positive.

**Comment by shahab-sarmashghi** [comment] 2023-09-28 16:01
Sorry, I got very busy and this slipped my mind. Regarding `Segment_Mean` it should be in log2ratio scale so you get positive values for amplifications (copy number > ploidy), and negative values for deletions (copy number < ploidy). This is somehow a common convention but I should have clarified this, the README is updated now. Please try this and let me know if the issue is resolved. If BISCUT can find actual selection peaks that pass the significance threshold, you should get `.txt` files under your CANCERTYPE folder (not just `.pdf` files).

**Comment by fswirsky** [comment] 2023-09-29 14:47
No worries and thank you, I have now rerun it and it worked perfectly! I was having a look through the paper linked in the readme and was wondering how you generated the plots in Fig. 2d as they are a really elegant way of displaying the peaks found. Thank you again.

**Comment by shahab-sarmashghi** [comment] 2023-09-29 14:58
Glad to hear that!

@juliannshih, do you have a script for generating the figure that visualizes identified peaks (Fig. 2d) or was it mostly your art/illustrator magic?

**Comment by fswirsky** [comment] 2023-10-09 13:05
Hi again, just a quick question about calculating the segment mean; because the total CN can be 0, in this case the log2 result would be undefined - is there a substitution that's best for the BISCUT algorithm to use in this situation?

**Comment by shahab-sarmashghi** [comment] 2023-10-09 16:08
I would replace those 0s with something small but non-zero like 0.1 (before taking the log2). Since BISCUT is mainly concerned with the length of arm-level events which are mostly low-level in terms of amplitude, the actual value doesn't matter as long as it remains a deletion that passes the amplitude threshold.

**Closed** 2023-11-02 16:16 UTC
